<?xml version="1.0"?>

<footer>
    <p>
        <link href="http://sourceforge.net/" 
            icon="http://sourceforge.net/sflogo.php?group_id=109360&amp;type=1"
            width="88" height="31" alt="Sourceforge.net"/>
            
        <link href="http://validator.w3.org/check/referer"
            icon="/images/xhtml.png" width="88" height="31"
            alt="Valid XHTML"/>
    
        <link href="http://www.w3c.org/"
            icon="/images/css.png" width="88" height="31"
            alt="Valid CSS"/>

	<image href="http://www.glendale.org.uk/counters/yagsbook.php" width="0" height="0"/>
    </p>   
</footer>